import { test, expect } from "@playwright/test"
import { connectToDatabase, closeConnection, executeQuery } from "../infrastructure/db"

test("database connection test", async({}) => {
    await test.step('Connect to db', async () => {
        await connectToDatabase();
    });

    await test.step('Create table', async () => {
        await executeQuery(
            `CREATE TABLE IF NOT EXISTS users (
                id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL
            );`
        );
    });

    await test.step('Insert users to table', async () => {
        await executeQuery(
            `INSERT INTO users (name) VALUES ('Seba'), ('Janek');`
        );
    });

    await test.step('Get users from table', async () => {
        const resp = await executeQuery(`SELECT * FROM users;`);
        console.log(resp.rows);
        expect(resp.rows.some(
            (row: { id: number; name: string }) => row.name === "Seba")
        ).toBeTruthy();
    });

    await test.step('Drop table', async () => {
        await executeQuery(`DROP TABLE users;`);
    });

    await test.step('Close db connection', async () => {
        await closeConnection();
    });
});